{% set name = "simple-di" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/simple_di-{{ version }}.tar.gz
  sha256: 192b999dee4cd4fb11a5d861165caad02d8f0617c0f806fc5b09f905f1a03ca0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    ## Converting the recipe to noarch: only build for python>=3.7
    # - dataclasses  # [py<37]
    # - types-dataclasses  # [py<37]

test:
  imports:
    - simple_di
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bentoml/simple_di
  summary: simple dependency injection library
  license: Apache-2.0
  license_file: LICENSE
  description: |
    A simple, strictly typed dependency injection library.

    PyPI: [https://pypi.org/project/simple-di/](https://pypi.org/project/simple-di/)

  doc_url: https://github.com/bentoml/simple_di
  dev_url: https://github.com/bentoml/simple_di

extra:
  recipe-maintainers:
    - sugatoray
